services:
    job:
        image: us-central1-docker.pkg.dev/satori-test-10-451404/docker-1/executor
        build: .
        container_name: welcome-packet-problem-3-job
        volumes:
            - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/key.json:ro
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
        env_file:
            - .env
        ports:
            - 8080:8080
        command: job.py
    server:
        image: us-central1-docker.pkg.dev/satori-test-10-451404/docker-1/executor
        build: .
        container_name: welcome-packet-problem-3-server
        volumes:
            - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/key.json:ro
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
        env_file:
            - .env
        ports:
            - 8080:8080
        command: server.py
