name: dbt/Image Build Push

on:
  push:
    branches:
      - master
      - dbt
    paths:
      - .github/workflows/dbt-image-build-push.yaml
      - dbt/**
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  IMAGE_TAG: us-central1-docker.pkg.dev/satori-test-10-451404/docker-1/dbt

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_TAG }}
          context: ./dbt
          target: production
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
