name: Executor/Cloud Run Deploy

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/executor-cloud-run-deploy.yaml
      - executor/**
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  IMAGE_TAG: us-central1-docker.pkg.dev/satori-test-10-451404/docker-1/ingestion--mailchimp
  SERVICE_NAME: ingestion--mailchimp

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_TAG }}
          context: ./executor
          target: production
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cloud-run-service-deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: echo "GCP_SA=$(gcloud config list account --format "value(core.account)")" >> $GITHUB_ENV

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_TAG }}
          region: us-central1
          timeout: 30s
          secrets: |
            MAILCHIMP_API_KEY=MAILCHIMP_API_KEY:latest
          flags: |
            --service-account ${{ env.GCP_SA }}
            --args server
            --cpu 1
            --memory 512Mi

      - run: |-
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --region=us-central1 \
            --update-env-vars=PUBLIC_URL=${{ steps.deploy.outputs.url }}

      - run: |-
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region=us-central1 \
            --member="allUsers" \
            --role="roles/run.invoker"
